name: example
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  multi_network_image:
    path: ../

dev_dependencies:
  leancode_lint: ^15.0.0

flutter:
  uses-material-design: true
